### ISSUE TITLE
directory issue

### ISSUE THREAD

**Issue by 77asadian** [diambra/arena#39] opened 2022-10-22 13:32 UTC
Hi,

I'd keep receiving this error when I'm creating a new environment like doapp:
"Error: Cannot open "/opt/diambraArena/roms/doapp.zip": No such file or directory."

Can you please tell me What I should do?

**Comment by alexpalms** [comment] 2022-10-22 13:36
Hi @77asadian have you downloaded the game rom as explained in the docs here: https://docs.diambra.ai/#download-game-roms-and-check-validity

**Comment by 77asadian** [comment] 2022-10-22 13:43
> 
I think I have. I had to create some new folders and rename them to make this prompt work!

![image](https://user-images.githubusercontent.com/116443211/197342269-38d09d92-389c-49da-add1-7e7ec292f5c8.png)

**Comment by alexpalms** [comment] 2022-10-22 13:47
You could have placed the roms wherever you prefer, `your/roms/path` is just a placeholder/example.

So it appears you created the following nested folders `C:\Users\HamidReza\your\roms\local\path\` where you put your roms, correct?

**Comment by 77asadian** [comment] 2022-10-22 13:49
> You could have placed the roms wherever you prefer, `your/roms/path` is just a placeholder/example.
> 
> So it appears you created the following nested folders `C:\Users\HamidReza\your\roms\local\path\` where you put your roms, correct?

OOPS!
No, This is the right directory:
"C:\Users\HamidReza\.diambra\roms\your\roms\local\path"

**Comment by alexpalms** [comment] 2022-10-22 13:52
Ok, anyways, you could also create a simple `C:\Desktop\roms\` folder where to place them. This path is then needed by the CLI: when you run a script you need to specify it in this way:
`diambra run -r C:\Users\HamidReza.diambra\roms\your\roms\local\path python script.py`
where`script.py` is the name of the script you want to run.

**Comment by 77asadian** [comment] 2022-10-22 13:54
> Ok, anyways, you could also create a simple `C:\Desktop\roms\` folder where to place them. This path is then needed by the CLI: when you run a script you need to specify it in this way:
> 
> `diambra run -r C:\Users\HamidReza.diambra\roms\your\roms\local\path python script.py`
> 
> where`script.py` is the name of the script you want to run.
> 
> Can you try this way?

Actually, I'm using jupyter notebook. Can you please recommend a CLI so that I can use it in jupyter notebook?

**Comment by alexpalms** [comment] 2022-10-22 13:56
Are you using jupyter notebook from the shell of within IDE like VSCode?

**Comment by alexpalms** [comment] 2022-10-22 13:59
Guidelines on how to use jupyter notebooks are described in our docs here: https://docs.diambra.ai/gettingstarted/#using-python-notebooks

**Comment by 77asadian** [comment] 2022-10-22 14:04
> Are you using jupyter notebook from the shell of within IDE like VSCode?

1. I'm using anaconda. I tried to make a special environment for this platform. Then I follow the installation instructions. I'm currently running jupyter notebook with this command:
`diambra run jupyter notebook`

2. I tried your recommended prompts. I made a script.py file and fill it with the base script in the documentation. Now I did not receive the former error but another one just appeared:

![image](https://user-images.githubusercontent.com/116443211/197343308-813776ac-ddf3-46c6-bcf4-94300ca8f787.png)


I hope I don't butter you.

**Comment by alexpalms** [comment] 2022-10-22 14:06
We are happy to help, no bother at all! 😄 

There are a few problems:
1) to use jupyter notebook user `diambra run -r C:\Users\HamidReza.diambra\roms\your\roms\local\path jupyter notebook`
2) the command you are using is wrong, take a look again at the command I sent you, yours is missing `python `

**Comment by 77asadian** [comment] 2022-10-22 14:13
> 1. diambra run -r

Thank you! It worked.
Now I just want to connect this code to Docker. How can I do that?

**Comment by alexpalms** [comment] 2022-10-22 14:15
Just to make sure this issue can be closed, where you able to properly run the script so that the environment loaded and you where able to interact with it?

**Comment by 77asadian** [comment] 2022-10-22 14:19
> Just to make sure this issue can be closed, where you able to properly run the script so that the environment loaded and you where able to interact with it?
> 
> If you could share a screenshot would be great

I don't properly understand your question, but I used this command: `diambra run -r C:\Users\HamidReza.diambra\roms\your\roms\local\path jupyter notebook` to perform the script in jupyter notebook.

Now, I'm performing the `env.render` line and I don't see anything. 
Here is a screenshot from jupyter notebook:

![image](https://user-images.githubusercontent.com/116443211/197344165-b838ecca-bf2a-4580-8be4-edacf5244f96.png)

**Comment by alexpalms** [comment] 2022-10-22 14:21
Ok so the environment is being loaded and runs. Great! I'll close the issue for this.

**Closed by alexpalms** 2022-10-22 14:21 UTC

**Comment by alexpalms** [comment] 2022-10-22 14:23
Regarding the rendering and other aspects, let's talk about it on a dedicated issue or on our discord server, whatever you prefer.

**Comment by 77asadian** [comment] 2022-10-22 14:29
> Regarding the rendering and other aspects, let's talk about it on a dedicated issue or on our discord server https://discord.gg/tFDS2UN5sv, whatever you prefer.

Thank you for your help man.
I made an issue so that anyone who has the same problem, refer to that.

**Comment by alexpalms** [comment] 2022-10-22 14:33
Perfect! The issue is the following: https://github.com/diambra/arena/issues/40
